name: T-Rex APK erstellen (ZIP)

on:
  workflow_dispatch:  # sorgt für den "Run workflow"-Knopf

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Repository auschecken
        uses: actions/checkout@v4

      - name: JDK 17 installieren
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'

      # Android SDK (cmdline-tools) + Lizenzen + benötigte Pakete
      - name: Android SDK vorbereiten & Lizenzen akzeptieren
        shell: bash
        run: |
          set -e
          yes | sudo ${ANDROID_HOME}/cmdline-tools/latest/bin/sdkmanager --licenses || true
          sudo ${ANDROID_HOME}/cmdline-tools/latest/bin/sdkmanager \
            "platform-tools" "platforms;android-34" "build-tools;34.0.0"

      # ZIP-Datei entpacken (Name anpassen, falls du sie anders genannt hast)
      - name: ZIP entpacken
        run: unzip -o TrexRoarApp_v2.zip

      # Projektordner automatisch finden (Ordner mit gradlew)
      - name: Projektordner finden
        id: findproj
        shell: bash
        run: |
          set -e
          PROJECT_DIR=$(dirname "$(git ls-files -z | tr '\0' '\n' | grep -m1 '/gradlew$')" || true)
          if [ -z "$PROJECT_DIR" ]; then
            PROJECT_DIR=$(dirname "$(find . -maxdepth 3 -type f -name gradlew | head -n1)" || true)
          fi
          if [ -z "$PROJECT_DIR" ]; then
            echo "Kein gradlew gefunden. Bitte prüfe die ZIP-Struktur." >&2
            exit 1
          fi
          echo "PROJECT_DIR=$PROJECT_DIR" >> $GITHUB_ENV
          echo "Gefundener Projektordner: $PROJECT_DIR"

      - name: Debug-APK bauen
        working-directory: ${{ env.PROJECT_DIR }}
        run: |
          chmod +x gradlew
          ./gradlew --version
          ./gradlew assembleDebug

      - name: APK hochladen
        uses: actions/upload-artifact@v4
        with:
          name: trex-debug-apk
          path: |
            ${{ env.PROJECT_DIR }}/app/build/outputs/apk/debug/*.apk
            ${{ env.PROJECT_DIR }}/**/build/outputs/apk/debug/*.apk
          if-no-files-found: error
