- name: Namespace/SDK prüfen und nur bei Bedarf patchen
        shell: bash
        run: |
          set -e
          APP="$PROJECT_DIR/app"
          MANIFEST="$APP/src/main/AndroidManifest.xml"

          # Package aus Manifest lesen (Fallback)
          PKG=""
          if [ -f "$MANIFEST" ]; then
            PKG=$(grep -oP 'package="\K[^"]+' "$MANIFEST" || true)
          fi
          [ -z "$PKG" ] && PKG="com.example.app"

          # Gradle-Datei finden (KTS oder Groovy)
          FILE=""
          KTS=0
          if [ -f "$APP/build.gradle.kts" ]; then
            FILE="$APP/build.gradle.kts"; KTS=1
          elif [ -f "$APP/build.gradle" ]; then
            FILE="$APP/build.gradle"
          else
            echo "Keine build.gradle(.kts) gefunden – Schritt wird übersprungen."
            exit 0
          fi
          echo "Gefundene Gradle-Datei: $FILE"

          # Prüfen, ob bereits korrekt
          if grep -q 'namespace' "$FILE" \
             && grep -q 'compileSdk' "$FILE" \
             && grep -q 'targetSdk' "$FILE"; then
            echo "Namespace/SDK bereits gesetzt – nichts zu tun."
            exit 0
          fi

          # Nur bei Bedarf patchen (robust, ohne .new-Datei)
          if [ $KTS -eq 1 ]; then
            # Kotlin DSL
            sed -i.bak -E \
              -e "s/namespace *= *\"[^\"]+\"/namespace = \"$PKG\"/g" \
              -e "s/compileSdk *= *[0-9]+/compileSdk = 34/g" \
              -e "s/targetSdk *= *[0-9]+/targetSdk = 34/g" "$FILE" || true
            # Falls Einträge fehlen, minimal einfügen
            grep -q 'namespace' "$FILE" || awk -v ns="$PKG" '{print} /android[[:space:]]*\{/ && !done {print "    namespace = \"" ns "\""; done=1}' "$FILE" > "$FILE.tmp" && mv "$FILE.tmp" "$FILE"
            grep -q 'compileSdk' "$FILE" || awk '{print} /android[[:space:]]*\{/ && !done {print "    compileSdk = 34"; done=1}' "$FILE" > "$FILE.tmp" && mv "$FILE.tmp" "$FILE"
            grep -q 'targetSdk' "$FILE" || awk 'BEGIN{ins=0} /defaultConfig[[:space:]]*\{/ {print; print "        targetSdk = 34"; ins=1; next} {print}' "$FILE" > "$FILE.tmp" && mv "$FILE.tmp" "$FILE"
          else
            # Groovy DSL
            sed -i.bak -E \
              -e "s/namespace +\"[^\"]+\"/namespace \"$PKG\"/g" \
              -e "s/compileSdk +[0-9]+/compileSdk 34/g" \
              -e "s/targetSdk +[0-9]+/targetSdk 34/g" "$FILE" || true
            grep -q 'namespace' "$FILE" || awk -v ns="$PKG" '{print} /android[[:space:]]*\{/ && !done {print "    namespace \"" ns "\""; done=1}' "$FILE" > "$FILE.tmp" && mv "$FILE.tmp" "$FILE"
            grep -q 'compileSdk' "$FILE" || awk '{print} /android[[:space:]]*\{/ && !done {print "    compileSdk 34"; done=1}' "$FILE" > "$FILE.tmp" && mv "$FILE.tmp" "$FILE"
            grep -q 'targetSdk' "$FILE" || awk 'BEGIN{ins=0} /defaultConfig[[:space:]]*\{/ {print; print "        targetSdk 34"; ins=1; next} {print}' "$FILE" > "$FILE.tmp" && mv "$FILE.tmp" "$FILE"
          fi

          echo "Patch-Schritt abgeschlossen."
