name: T-Rex APK erstellen (ZIP)

on:
  workflow_dispatch:
  push:
    paths:
      - 'TrexRoarApp_*.zip'
      - '.github/workflows/**'

env:
  ZIP_NAME: TrexRoarApp_v2.zip

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Repository auschecken
        uses: actions/checkout@v4

      - name: JDK 17 installieren
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: "17"

      - name: Android SDK vorbereiten
        uses: android-actions/setup-android@v3

      - name: Tools installieren
        run: |
          sudo apt-get update
          sudo apt-get install -y unzip

      - name: ZIP entpacken
        run: |
          if [ ! -f "$ZIP_NAME" ]; then
            echo "::error ::$ZIP_NAME fehlt im Repository-Root"
            echo "Lade die ZIP ins Repo hoch oder ändere ZIP_NAME oben."
            exit 1
          fi
          unzip -q "$ZIP_NAME" -d extracted
          if [ -d extracted/app ]; then
            echo "PROJECT_DIR=extracted" >> $GITHUB_ENV
          else
            FIRST=$(ls -1 extracted | head -n1)
            echo "PROJECT_DIR=extracted/$FIRST" >> $GITHUB_ENV
          fi

      - name: Projekt vorbereiten (AndroidX/SDK/Theme)
        run: |
          cd "$PROJECT_DIR"
          echo "android.useAndroidX=true" >> gradle.properties
          echo "android.enableJetifier=true" >> gradle.properties

          GR="app/build.gradle"
          [ -f app/build.gradle.kts ] && GR="app/build.gradle.kts"

          sed -i 's/compileSdkVersion *[0-9][0-9]*/compileSdkVersion 34/g' "$GR" || true
          sed -i 's/targetSdkVersion *[0-9][0-9]*/targetSdkVersion 34/g' "$GR" || true
          sed -i 's/minSdkVersion *[0-9][0-9]*/minSdkVersion 24/g' "$GR" || true

          if ! grep -q "com.google.android.material" "$GR"; then
            printf '\n    implementation "com.google.android.material:material:1.12.0"\n' >> "$GR"
            printf '    implementation "androidx.core:core-splashscreen:1.0.1"\n' >> "$GR"
          fi

          mkdir -p app/src/main/res/values app/src/main/res/values-night
          cat > app/src/main/res/values/themes.xml <<'XML'
<resources xmlns:tools="http://schemas.android.com/tools">
  <style name="AppTheme" parent="Theme.Material3.DayNight.NoActionBar"/>
  <style name="Theme.TrexRoarApp" parent="AppTheme" tools:override="true"/>
</resources>
XML
          cp app/src/main/res/values/themes.xml app/src/main/res/values-night/themes.xml
          sed -i 's/android:theme="[^"]*"/android:theme="@style\/AppTheme"/g' app/src/main/AndroidManifest.xml || true

      - name: Debug-APK bauen
        run: |
          cd "$PROJECT_DIR"
          ./gradlew :app:assembleDebug --no-daemon

      - name: APK als Artefakt hochladen
        uses: actions/upload-artifact@v4
        with:
          name: trex-debug-apk
          path: ${{ env.PROJECT_DIR }}/app/build/outputs/apk/debug/*.apk
