name: T-Rex APK erstellen (ZIP)

on:
  workflow_dispatch:
  push:
    paths:
      - "TrexRoarApp_*.zip"
      - ".github/workflows/**"

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      ANDROID_HOME: ${{ runner.temp }}/android-sdk

    steps:
      - name: Repository auschecken
        uses: actions/checkout@v4

      - name: JDK 17 installieren
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'

      # Android CLI installieren + Lizenzen akzeptieren
      - name: Android SDK vorbereiten & Lizenzen akzeptieren
        shell: bash
        run: |
          set -eux
          mkdir -p "${ANDROID_HOME}/cmdline-tools"
          cd "${ANDROID_HOME}/cmdline-tools"
          curl -L -o sdk.zip "https://dl.google.com/android/repository/commandlinetools-linux-11076708_latest.zip"
          unzip -q sdk.zip
          mv cmdline-tools latest
          yes | "${ANDROID_HOME}/cmdline-tools/latest/bin/sdkmanager" --sdk_root="${ANDROID_HOME}" --licenses >/dev/null
          yes | "${ANDROID_HOME}/cmdline-tools/latest/bin/sdkmanager" --sdk_root="${ANDROID_HOME}" \
               "platform-tools" "platforms;android-34" "build-tools;34.0.0"
          echo "${ANDROID_HOME}/platform-tools" >> "$GITHUB_PATH"
          echo "${ANDROID_HOME}/build-tools/34.0.0" >> "$GITHUB_PATH"

      # ZIP finden + entpacken
      - name: ZIP-Datei finden
        id: findzip
        shell: bash
        run: |
          set -eux
          ZIP=$(ls -1 TrexRoarApp_*.zip | head -n1)
          echo "zip=$ZIP" >> "$GITHUB_OUTPUT"

      - name: ZIP entpacken
        shell: bash
        run: |
          set -eux
          mkdir -p "$RUNNER_TEMP/appsrc"
          unzip -q "${{ steps.findzip.outputs.zip }}" -d "$RUNNER_TEMP/appsrc"

      # Projektordner + Build-Tool erkennen
      - name: Projektordner + Gradle-Datei finden
        id: findproj
        shell: bash
        run: |
          set -eux
          ROOT="$RUNNER_TEMP/appsrc"

          # 1) Wrapper?
          if GRADLEW=$(find "$ROOT" -type f -name "gradlew" | head -n1); then
            echo "has_wrapper=true" >> "$GITHUB_OUTPUT"
            echo "project_dir=$(dirname "$GRADLEW")" >> "$GITHUB_OUTPUT"
            exit 0
          fi

          # 2) settings.gradle(.kts)?
          if SETTINGS=$(find "$ROOT" -type f \( -name "settings.gradle" -o -name "settings.gradle.kts" \) | head -n1); then
            echo "has_wrapper=false" >> "$GITHUB_OUTPUT"
            echo "project_dir=$(dirname "$SETTINGS")" >> "$GITHUB_OUTPUT"
            exit 0
          fi

          echo "::error::Keine build.gradle(.kts) / settings.gradle(.kts) gefunden!"
          exit 1

      # Sicherstellen, dass das Projekt das SDK findet
      - name: Gradle-Konfig automatisch fixen (SDK/Android)
        shell: bash
        run: |
          set -eux
          PROJECT_DIR="${{ steps.findproj.outputs.project_dir }}"
          echo "sdk.dir=${ANDROID_HOME}" > "${PROJECT_DIR}/local.properties"

      # Nur falls kein Wrapper vorhanden: Gradle CLI installieren (mit zip/unzip Fix)
      - name: Falls nötig Gradle CLI installieren
        if: steps.findproj.outputs.has_wrapper == 'false'
        shell: bash
        run: |
          set -eux
          sudo apt-get update
          sudo apt-get install -y zip unzip
          curl -s "https://get.sdkman.io" | bash
          source "$HOME/.sdkman/bin/sdkman-init.sh"
          sdk install gradle 8.7
          echo "$HOME/.sdkman/candidates/gradle/current/bin" >> "$GITHUB_PATH"
          gradle -v

      # Build
      - name: Debug-APK bauen
        working-directory: ${{ steps.findproj.outputs.project_dir }}
        shell: bash
        run: |
          set -eux
          if [ "${{ steps.findproj.outputs.has_wrapper }}" = "true" ]; then
            chmod +x ./gradlew
            ./gradlew --version
            ./gradlew assembleDebug
          else
            gradle --version
            gradle assembleDebug
          fi

      # Artefakt hochladen
      - name: APK hochladen
        uses: actions/upload-artifact@v4
        with:
          name: trex-debug-apk
          path: |
            ${{ steps.findproj.outputs.project_dir }}/**/build/outputs/**/*.apk
          if-no-files-found: error

      # Bei Fehlern: Gradle-Logs hochladen (optional, hilft beim Debuggen)
      - name: Build-Logs hochladen (bei Fehlern)
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: gradle-logs
          path: |
            ${{ steps.findproj.outputs.project_dir }}/**/build/**/reports
            ${{ steps.findproj.outputs.project_dir }}/**/build/**/outputs/**/*.txt
          if-no-files-found: ignore
